updated the announcement
CodeDrills-CD/codedrills-recommender pull request #25
Opened 2022-10-11 17:34 UTC by ryuusama09

2022-10-11 20:48 UTC, cdbalaji requested changes
Please remove target folder.

2022-10-11 20:48 UTC, cdbalaji commented on src/main/resources/templates/recommender.ftl
> +          <h4 class="alert-heading">Announcement!</h4>
We can have "We are now open source" instead of "Announcement!"

2022-10-11 20:48 UTC, cdbalaji commented on src/main/resources/templates/recommender.ftl
> +          <a href ="https://github.com/CodeDrills-CD/codedrills-recommender">< p> CodeDrills recommender is now open source! Visit the GitHub repository to contribute or report issues and feature req
Add the link to only the "Github repository" part instead of to the whole announcement.

2022-10-12 03:13 UTC, ryuusama09 commented
Alright @cdbalaji , I am closing this PR and sending a new one

2022-10-12 03:13 UTC, closed without merging